// Code generated by Slice Machine. DO NOT EDIT.

import Cart from './Cart/index.svelte';
import Picture from './Picture/index.svelte';
import Product from './Product/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	cart: Cart,
	picture: Picture,
	product: Product,
	rich_text: RichText
};
